version: '2'
services:
  redis:
    image: 'redis'
  backend:
    build: backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    ports:
      - "3000:3000"
    links:
      - redis
  frontend:
    build: frontend
    ports:
      - "8080:80"