version: '2'
services:
  redis:
    image: 'redis'
  backend:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    ports:
      - "8080:8080"
    links:
      - redis